In [1]:
from spending_tracker.data_ingestion import pdf_parsing
from spending_tracker.data_processing import chase
from pathlib import Path

In [2]:
user = "Taj"
account = "Chase"
account_id = "69448147"
month = "July-26"

data_path = Path().resolve().parent / "data" / "transactions" / "raw" / user / account / account_id / month / "statement.pdf"
data_save_path = Path().resolve().parent / "data" / "transactions" / "processed" / user / account / account_id / month / "statement.csv"
print(data_path)

/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/raw/Taj/Chase/69448147/July-26/statement.pdf

In [3]:
df = pdf_parsing.chase_pdf_to_dataframe(data_path)

In [4]:
df.head()

,date,transaction_details,amount,balance
0,01 Jul 2026,Interest earned\nInterest,+£21.38,"£10,407.24"
1,06 Jul 2026,From Taj's Account\nTransfer,"+£1,600.00","£12,007.24"
2,06 Jul 2026,To AMERICAN EXP 3773 - PB658258159641217\nPayment,"-£2,084.16","£9,923.08"
3,07 Jul 2026,To Taj Patel - Chase\nPayment,-£500.00,"£9,423.08"
4,08 Jul 2026,To Vithushan Maurice - Chase\nPayment,"-£1,000.00","£8,423.08"

In [5]:
df.tail()

,date,transaction_details,amount,balance
19,29 Jul 2026,Mercedes-Benz - S0RP04TAJ014570102\nDirect Debit,-£92.19,"£5,778.50"
20,29 Jul 2026,From Boosted Saver\nTransfer,"+£2,082.00","£7,860.50"
21,29 Jul 2026,To Taj Patel - Chase\nPayment,-£100.00,"£7,760.50"
22,29 Jul 2026,To Trading 212 - 212TOZWC2212T\nPayment,"-£1,500.00","£6,260.50"
23,30 Jul 2026,To Taj Jamie Rajesh Patel - Chase\nPayment,-£100.00,"£6,160.50"

In [6]:
cleaned_df = chase.clean_transaction_dataframe(df, account_id=account_id, user=user)

In [9]:
cleaned_df.head(20)

,event_id,date,merchant,type,category,amount,other_details,account_id,user,raw_merchant,raw_amount,bank
0,fb641f97fd734c92205170a5df4c5800a8d0d9b6dc112a...,2026-07-01,Interest earned,Interest,None,-21.38,,69448147,Taj,Interest earned,-21.38,Chase Bank
1,1051b7a497136c7793f0d3623f8ad663d0363e48a1ea2c...,2026-07-06,From Taj's Account,Transfer,None,-1600.00,,69448147,Taj,From Taj's Account,-1600.00,Chase Bank
2,adc90a862debcae27e6e8556070de511741fd4435287f1...,2026-07-06,To AMERICAN EXP 3773 - PB658258159641217,Payment,None,2084.16,,69448147,Taj,To AMERICAN EXP 3773 - PB658258159641217,2084.16,Chase Bank
3,f1211216911d575fa379d31f2a2df6ab70550b111c8f1a...,2026-07-07,To Taj Patel - Chase,Payment,None,500.00,,69448147,Taj,To Taj Patel - Chase,500.00,Chase Bank
4,3dca9a0916bf03484ede934699ed1a7f4c145be65b6f34...,2026-07-08,To Vithushan Maurice - Chase,Payment,None,1000.00,,69448147,Taj,To Vithushan Maurice - Chase,1000.00,Chase Bank
5,cb9070465db36417dfc131d6628e2695d1f42a653aaecd...,2026-07-09,From GUJRATI ARYA - KHSECDEP180626,Payment,None,-500.00,,69448147,Taj,From GUJRATI ARYA - KHSECDEP180626,-500.00,Chase Bank
6,abf7023cf07a3807145f9eb57a3095d41f1a5d0b241049...,2026-07-10,The Gym Group - A444110C-THE-GYM,Direct Debit,None,19.99,,69448147,Taj,The Gym Group - A444110C-THE-GYM,19.99,Chase Bank
7,574fd36a6fca46a5d30eecda1bf0e4a503d2ab43fa21bf...,2026-07-10,From Taj Patel - CHASE,Payment,None,-471.30,,69448147,Taj,From Taj Patel - CHASE,-471.30,Chase Bank
8,c295c245e8953ac807541880c90622b937a03507276db9...,2026-07-10,From PAYPAL - PPWDL5U52222228JF8,Payment,None,-491.00,,69448147,Taj,From PAYPAL - PPWDL5U52222228JF8,-491.00,Chase Bank
9,6997a77081a3e9f431714f2e05029eafa839becc559232...,2026-07-13,From PARVEZ S A - FOOD,Payment,None,-235.00,,69448147,Taj,From PARVEZ S A - FOOD,-235.00,Chase Bank
10,d7dc6ea10cf655e93b8fce492d3536264fef47fa0dbaf1...,2026-07-16,Gc Re Klarna Financial Servicesuk - A477SX2-GI...,Direct Debit,None,5.25,,69448147,Taj,Gc Re Klarna Financial Servicesuk - A477SX2-GI...,5.25,Chase Bank
11,4b9b68d0d404c9bea6ad8a42bdd44a7778c9e672090164...,2026-07-21,From,Payment,None,-3465.53,,69448147,Taj,From,-3465.53,Chase Bank
12,ca0fe11def14fbae463f4c795834cbe46508c547e3da59...,2026-07-21,To Mr Rajesh Patel - Chase,Payment,None,350.00,,69448147,Taj,To Mr Rajesh Patel - Chase,350.00,Chase Bank
13,432e5775abce5ac57c55c5f97e12616341addee94569b6...,2026-07-21,To Taj Patel - Chase,Payment,None,1250.00,,69448147,Taj,To Taj Patel - Chase,1250.00,Chase Bank
14,cee2fce93052ec6be98bc68c9bf286e0a22e7dc26c235a...,2026-07-22,From Chase Saver,Transfer,None,-1123.42,,69448147,Taj,From Chase Saver,-1123.42,Chase Bank
15,f549b173843c540e25559f8f73f19653ee50d329f11c24...,2026-07-28,Tabeo - EEZXNN5-754192-BON,Direct Debit,None,97.19,,69448147,Taj,Tabeo - EEZXNN5-754192-BON,97.19,Chase Bank
16,ee69984fa046a8f3cc0635f56abc5ca745bafabd780fbe...,2026-07-28,Barclays - 5186528489312855,Direct Debit,None,25.00,,69448147,Taj,Barclays - 5186528489312855,25.00,Chase Bank
17,ca234307b1f777bafe36cca758a25dc9d7685172d7d614...,2026-07-28,From Boosted Saver,Transfer,None,-908.79,,69448147,Taj,From Boosted Saver,-908.79,Chase Bank
18,84e494dd182a36bfbca231f093bb3da5aac0f82690c71b...,2026-07-28,To Trading 212 - 212TOXTLM212T,Payment,None,8000.00,,69448147,Taj,To Trading 212 - 212TOXTLM212T,8000.00,Chase Bank
19,4593e830d4c8596a7457036ab156da1a298202b3e0c083...,2026-07-29,Mercedes-Benz - S0RP04TAJ014570102,Direct Debit,None,92.19,,69448147,Taj,Mercedes-Benz - S0RP04TAJ014570102,92.19,Chase Bank

In [8]:
cleaned_df.to_csv(data_save_path, index=False)