In [1]:
from spending_tracker.data_ingestion import pdf_parsing
from pathlib import Path

In [2]:
user = "Taj"
account = "Chase_69448147"
month = "July-26"

data_path = Path().resolve().parent / "data" / "transactions" / "raw" / user / account / month / "statement.pdf"
print(data_path)

/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/raw/Taj/Chase_69448147/July-26/statement.pdf

In [3]:
df = pdf_parsing.chase_pdf_to_dataframe(data_path)

In [4]:
df.head()

,date,transaction_details,amount,balance
0,01 Jul 2026,Round up\nTransfer,-£0.46,"£2,336.52"
1,01 Jul 2026,Round up\nTransfer,-£0.20,"£2,336.32"
2,01 Jul 2026,"Samanvaya\nPurchase | IDR 840,950.00 | FX rate...",-£35.82,"£2,300.50"
3,01 Jul 2026,"Equipoise Resort & Spa\nPurchase | IDR 155,550...",-£6.63,"£2,293.87"
4,02 Jul 2026,Round up\nTransfer,-£0.82,"£2,293.05"

In [6]:
df.tail()

           date       transaction_details  amount  balance
72  18 Jul 2026         Vb Sons\nPurchase  -£0.64  £152.53
73  19 Jul 2026        Round up\nTransfer  -£0.71  £151.82
74  20 Jul 2026  Apple / iTunes\nPurchase  -£1.29  £150.53
75  22 Jul 2026        Round up\nTransfer  -£0.92  £149.61
76  23 Jul 2026         Vb Sons\nPurchase  -£3.08  £146.53