In [1]:
from spending_tracker.data_ingestion import pdf_parsing
from spending_tracker.data_processing import chase
from pathlib import Path

In [2]:
user = "Taj"
account = "Chase"
account_id = "69448147"
month = "July-26"

data_path = Path().resolve().parent / "data" / "transactions" / "raw" / user / account / account_id / month / "statement.pdf"
data_save_path = Path().resolve().parent / "data" / "transactions" / "processed" / user / account / account_id / month / "statement.csv"
print(data_path)

/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/raw/Taj/Chase/69448147/July-26/statement.pdf

In [3]:
df = pdf_parsing.chase_pdf_to_dataframe(data_path)

In [4]:
df.head()

,date,transaction_details,amount,balance
0,01 Jul 2026,Round up\nTransfer,-£0.46,"£2,336.52"
1,01 Jul 2026,Round up\nTransfer,-£0.20,"£2,336.32"
2,01 Jul 2026,"Samanvaya\nPurchase | IDR 840,950.00 | FX rate...",-£35.82,"£2,300.50"
3,01 Jul 2026,"Equipoise Resort & Spa\nPurchase | IDR 155,550...",-£6.63,"£2,293.87"
4,02 Jul 2026,Round up\nTransfer,-£0.82,"£2,293.05"

In [5]:
df.tail()

           date       transaction_details  amount  balance
72  18 Jul 2026         Vb Sons\nPurchase  -£0.64  £152.53
73  19 Jul 2026        Round up\nTransfer  -£0.71  £151.82
74  20 Jul 2026  Apple / iTunes\nPurchase  -£1.29  £150.53
75  22 Jul 2026        Round up\nTransfer  -£0.92  £149.61
76  23 Jul 2026         Vb Sons\nPurchase  -£3.08  £146.53

In [6]:
cleaned_df = chase.clean_transaction_dataframe(df, account_id=account_id, user=user)

In [7]:
cleaned_df.head(10)

,event_id,date,merchant,type,category,amount,other_details,account_id,user,raw_merchant,raw_amount,bank
0,4ff7296f-3b09-4dea-b7c8-a3247728e871,2026-07-01,Round up,Transfer,None,0.46,,69448147,Taj,Round up,0.46,Chase Bank
1,142ac9ef-7ce0-46c1-8556-86e7088892a3,2026-07-01,Round up,Transfer,None,0.20,,69448147,Taj,Round up,0.20,Chase Bank
2,5d284cc1-8912-4cc4-9da4-fbe5223ff981,2026-07-01,Samanvaya,Purchase,None,35.82,"IDR 840,950.00 | FX rate £1 = IDR 23,477.4851",69448147,Taj,Samanvaya,35.82,Chase Bank
3,65f53cba-122c-4043-9103-9aed1a03b2c8,2026-07-01,Equipoise Resort & Spa,Purchase,None,6.63,"IDR 155,550.00 | FX rate £1 = IDR 23,462.0618",69448147,Taj,Equipoise Resort & Spa,6.63,Chase Bank
4,6d3f485c-f7b4-40ec-ac5b-917b169e4201,2026-07-02,Round up,Transfer,None,0.82,,69448147,Taj,Round up,0.82,Chase Bank
5,a39726a2-4731-4ec6-bc4c-cc4ce61891d1,2026-07-02,Round up,Transfer,None,0.39,,69448147,Taj,Round up,0.39,Chase Bank
6,279f852d-e4b2-407f-8ba1-5365113a455e,2026-07-02,Round up,Transfer,None,0.41,,69448147,Taj,Round up,0.41,Chase Bank
7,c4859362-83ab-40c2-977d-40a9f9b1f6a5,2026-07-02,Samanvaya,Purchase,None,1.80,"IDR 42,350.00 | FX rate £1 = IDR 23,528.3046",69448147,Taj,Samanvaya,1.80,Chase Bank
8,acf027a1-c8db-4f39-a758-8357fed505dd,2026-07-02,Samanvaya,Purchase,None,11.54,"IDR 272,250.00 | FX rate £1 = IDR 23,592.1391",69448147,Taj,Samanvaya,11.54,Chase Bank
9,2da85e91-687f-49f8-9ab9-de83b461b7bd,2026-07-03,Round up,Transfer,None,0.26,,69448147,Taj,Round up,0.26,Chase Bank

In [8]:
cleaned_df.to_csv(data_save_path, index=False)