#### Notebook to fetch data from Storage bucket, process and upload to dashboard.

In [1]:
from pathlib import Path
from spending_tracker.data_processing.statements import parse_and_clean_batch
from spending_tracker.database import transactions as transactions_db
from spending_tracker.database import supabase_client
from spending_tracker.data_ingestion import csv_parsing

In [2]:
data_path = Path().resolve().parent / "data"
month = "October-26"
bucket_name = "spending-tracker"

In [3]:
bucket = supabase_client.load_bucket(bucket_name)

#### Clean Transactions and generate Metadata

In [4]:
data_fetched = transactions_db.fetch_transactions_from_bucket(month=month,
                                               bucket=bucket,
                                               data_home=data_path)

for key in data_fetched:
    print(key)

data/transactions/raw/Joint/Nationwide/03076275/October-26/statement.csv
data/transactions/raw/Radhika/Nationwide/34490057/October-26/statement.csv
data/transactions/raw/Taj/Amex/52006/October-26/statement.csv
data/transactions/raw/Taj/Chase/33053200/October-26/statement.csv

In [5]:
parse_and_clean_batch(data_home=data_path,
                      specific_month=month)

Processing Joint/Nationwide/03076275/October-26
Processing Radhika/Nationwide/34490057/October-26
Processing Taj/Amex/52006/October-26
Processing Taj/Chase/33053200/October-26

#### Upload to Database

In [6]:
db_client = supabase_client.load_supabase_client()

In [7]:
processed_transactions_data_home = data_path / "transactions" / "processed"
transaction_metadata_home = data_path / "transactions_metadata"

In [8]:
transactions_df = csv_parsing.load_csv_in_batch(processed_transactions_data_home,
                                                specific_month=month,
                                                dtype_kwargs={
                                                    "account_id": str,
                                                })

transactions_metadata_df = csv_parsing.load_csv_in_batch(transaction_metadata_home,
                                                         specific_month=month,
                                                         dtype_kwargs={
                                                             "account_id": str,
                                                         })

In [9]:
transactions_df.head(10)

,event_id,date,month,account_id,user,bank,merchant,other_details,type,amount
0,e1bf6e35e0934977ac8ca9789e5d4b6dbfbf0dcb5b44e2...,2026-10-01,October-26,03076275,Joint,Nationwide,Krave Dessert Cafe Northwood GB,APPLEPAY 9160,NaN,-28.97
1,ca705b361ed09fd2d679b6feca824508939b16038c5615...,2026-10-03,October-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-9.25
2,b77250f3bcf3001f05de37ba371c9437c178ef335969cb...,2026-10-05,October-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 9160,NaN,-1.39
3,07f3e8e9899b57330bfe1bd692dfe6e51b02cda3b7d7cd...,2026-10-05,October-26,03076275,Joint,Nationwide,WAITROSE STORES HARROW WEALD GB,APPLEPAY 4914,NaN,-6.75
4,50655879e57e104b4432882720ae7c777e5e50a86a1c84...,2026-10-05,October-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 9160,NaN,-9.90
5,785d432b04ce2d98fa04a2e8441cf03b9d074b7678bcd8...,2026-10-06,October-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-9.05
6,6018554ff9244303b29acba463e4d008da6597c89494be...,2026-10-07,October-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-0.95
7,363bd928efff491bdb8b47d9b6670a02afae916394fa27...,2026-10-09,October-26,03076275,Joint,Nationwide,Hotto Potto London GB,APPLEPAY 4914,NaN,-34.76
8,35d7f245d0599e18582ecb69ee4378aab6b07c75ec6de5...,2026-10-09,October-26,03076275,Joint,Nationwide,Hotto Potto London GB,APPLEPAY 4914,NaN,-34.76
9,89fe39a21e6c3c65e416a2c127a4ced2a99894d9e46423...,2026-10-08,October-26,51016,Radhika,Amex,TFL TRAVEL CHARGE,TFL.GOV.UK/CP,NaN,-7.20

In [10]:
transactions_metadata_df.head(10)

,event_id,llm_merchant,llm_category,manual_merchant,manual_category,manual_amount,manual_date,hidden
0,e1bf6e35e0934977ac8ca9789e5d4b6dbfbf0dcb5b44e2...,Krave Dessert Cafe Northwood GB,dining,NaN,NaN,NaN,NaN,False
1,ca705b361ed09fd2d679b6feca824508939b16038c5615...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,NaN,False
2,b77250f3bcf3001f05de37ba371c9437c178ef335969cb...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,NaN,False
3,07f3e8e9899b57330bfe1bd692dfe6e51b02cda3b7d7cd...,Waitrose,groceries,NaN,NaN,NaN,NaN,False
4,50655879e57e104b4432882720ae7c777e5e50a86a1c84...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,NaN,False
5,785d432b04ce2d98fa04a2e8441cf03b9d074b7678bcd8...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,NaN,False
6,6018554ff9244303b29acba463e4d008da6597c89494be...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,NaN,False
7,363bd928efff491bdb8b47d9b6670a02afae916394fa27...,Hotto Potto London GB,dining,NaN,NaN,NaN,NaN,False
8,35d7f245d0599e18582ecb69ee4378aab6b07c75ec6de5...,Hotto Potto London GB,dining,NaN,NaN,NaN,NaN,False
9,89fe39a21e6c3c65e416a2c127a4ced2a99894d9e46423...,TFL TRAVEL CHARGE,transport,NaN,NaN,NaN,NaN,False

In [11]:
transactions_df.shape

(29, 10)

In [12]:
transactions_metadata_df.shape

(29, 8)

In [13]:
transactions_db.upload_transactions_to_db(transactions_df, 
                                       db_client, 
                                       table_name="transactions")
transactions_db.upload_transactions_to_db(transactions_metadata_df, 
                                       db_client, 
                                       table_name="transactions_metadata",
                                       exclude_columns=["manual_merchant", "manual_category", "manual_amount", "manual_date", "hidden"])

APIResponse(data=[{'event_id': 'e1bf6e35e0934977ac8ca9789e5d4b6dbfbf0dcb5b44e275690c231fa3692dc4', 'llm_merchant': 'Krave Dessert Cafe Northwood GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'ca705b361ed09fd2d679b6feca824508939b16038c5615b42824e936157654af', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'b77250f3bcf3001f05de37ba371c9437c178ef335969cb3d4f8a3c397aae69d8', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '07f3e8e9899b57330bfe1bd692dfe6e51b02cda3b7d7cd4ec11c041a4fb038cf', 'llm_merchant': 'Waitrose', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '50655879e57e104b4432882720ae7c777e5e50a86a1c842d9e3f35475002fa57', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '785d432b04ce2d98fa04a2e8441cf03b9d074b7678bcd883f9d0ffc465514a8b', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '6018554ff9244303b29acba463e4d008da6597c89494be72ba238ad5b8320e44', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '363bd928efff491bdb8b47d9b6670a02afae916394fa2703180662c79b6a9482', 'llm_merchant': 'Hotto Potto London GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '35d7f245d0599e18582ecb69ee4378aab6b07c75ec6de5952bb6d83cb30e6354', 'llm_merchant': 'Hotto Potto London GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '89fe39a21e6c3c65e416a2c127a4ced2a99894d9e464232b2138e9c9bf031aca', 'llm_merchant': 'TFL TRAVEL CHARGE', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '2db3ab517b3d67d7cf04555984c8a4705a6f5cd281ae72adb671f7f37b0881e9', 'llm_merchant': 'ASDA', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '6830dfe59d257efac85dbdc5c114f483d289278e84f85da4820f3f3e5dcaebd4', 'llm_merchant': 'DVLA', 'llm_category': 'fixed_expense', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '73106b2b559996295bd9f5b72ca4dfa78e85362e0dca2357eb1e0ffb50f8edb7', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '794cfc1509c1467b9919ac59515de0db6d02ea8a4462b598050c7fec5a5dc665', 'llm_merchant': 'O2', 'llm_category': 'fixed_expense', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'e98a93311f89ee686bdddd94fdfad93f83eeb673fdf039079bcd2b30d9a99e6e', 'llm_merchant': 'THE GYM LTD', 'llm_category': 'fixed_expense', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'a2c7c916ba306ad351e56f8082f01ccd51cf68a680025b79fb8250c36918f4f4', 'llm_merchant': 'PAYBYPHONE RE BARNET ON S HATFIELD GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'dac29c6b4bf2175ec68272f73311d476b92753a13c8434c25f14d6ce7e500b34', 'llm_merchant': 'PAYBYPHONE RE BARNET ON S HATFIELD GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '53bb3ef18814224013553069e77a02398644a9cadfdedfd19b0dce869e44c1f0', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '170e4a24f3ee490d86bd034498bab66b9e8343203de7d396988dca498a799bae', 'llm_merchant': 'ARGOS 522975 MILTON', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '645e735772ab09b4ec4bf04f729510a8b713e4ef9280daf368188d720670982c', 'llm_merchant': 'TFL TRAVEL CHARGE', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '69cdcda2ff74763f9512dc8133dca5ef2e8aa284d29db2a2d7656e358620f528', 'llm_merchant': 'PAYMENT RECEIVED - THANK', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'cb726d0db9abe32cde74ee90b7447110b9a5de69fecf7ce9f6bb14df2d8102f9', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '19d6f0da4394ab2a1469892e59594cc018ef0acb2a9b505fc29432de2a123d14', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'c6e85e7e36977c779b6debcf2bcf610009ea2d6f12b71e9a026f78363e16c656', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'e6c9eb265011b4ddde5e084483fa519f54123c40b10b9ee0a52413209acad759', 'llm_merchant': 'THEBANKCHORLEYWOOD.CO. CHALFONT ST', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '6daee31838f8e1b34c35ab892b8542cf6515ffede1724d145ee4c7e019e5112b', 'llm_merchant': 'WM MORRISONS STORES - Q', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': '07f31ff129d3372771a25955089951bf40946037a96a5e5c467c2ed506c09658', 'llm_merchant': 'Greggs', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'ed83ecb4217232d14f41dab74fb4f5f4ba844eae6405f728d6f5a783d5f1517a', 'llm_merchant': 'Lakeland Climbing Cent', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}, {'event_id': 'dd565e6d6f1db53102befa99862e8c82ca6969e12a02a2696b4cc021b26b0e20', 'llm_merchant': 'Apple / iTunes', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': None, 'updated_at': '2026-10-11T11:18:49.375087+00:00', 'manual_date': None}], count=None)