#### Notebook to fetch data from Storage bucket, process and upload to dashboard.

In [1]:
from pathlib import Path
from spending_tracker.data_processing.statements import parse_and_clean_batch
from spending_tracker.database import transactions as transactions_db
from spending_tracker.database import supabase_client
from spending_tracker.data_ingestion import csv_parsing

In [2]:
data_path = Path().resolve().parent / "data"
month = "September-26"
bucket_name = "spending-tracker"

In [3]:
bucket = supabase_client.load_bucket(bucket_name)

#### Clean Transactions and generate Metadata

In [4]:
data_fetched = transactions_db.fetch_transactions_from_bucket(month=month,
                                               bucket=bucket,
                                               data_home=data_path)

for key in data_fetched:
    print(key)

data/transactions/raw/Joint/Nationwide/03076275/September-26/statement.csv
data/transactions/raw/Radhika/Nationwide/34490057/September-26/statement.csv
data/transactions/raw/Taj/Amex/52006/September-26/statement.csv
data/transactions/raw/Taj/Chase/33053200/September-26/statement.csv
data/transactions/raw/Taj/Chase/69448147/September-26/statement.csv

In [4]:
parse_and_clean_batch(data_home=data_path,
                      specific_month=month,
                      specific_bank="Chase")

Processing Taj/Chase/33053200/September-26
Processing Taj/Chase/69448147/September-26

#### Upload to Database

In [5]:
db_client = supabase_client.load_supabase_client()

In [6]:
processed_transactions_data_home = data_path / "transactions" / "processed"
transaction_metadata_home = data_path / "transactions_metadata"

In [7]:
transactions_df = csv_parsing.load_csv_in_batch(processed_transactions_data_home,
                                                specific_month=month,
                                                dtype_kwargs={
                                                    "account_id": str,
                                                })

transactions_metadata_df = csv_parsing.load_csv_in_batch(transaction_metadata_home,
                                                         specific_month=month,
                                                         dtype_kwargs={
                                                             "account_id": str,
                                                         })

In [8]:
transactions_df.head(10)

,event_id,date,month,account_id,user,bank,merchant,other_details,type,amount
0,bd111b5020ee5a1518b14556646d5602093349e4388f1f...,2026-09-01,September-26,03076275,Joint,Nationwide,DOMINO S PIZZA MILTON KEYNES GB,APPLEPAY 4914,NaN,-6.48
1,052ebaee9177cb9a0f194c620602fc7f808fe6bd08f08a...,2026-09-02,September-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-0.79
2,f6a0625d165905b80279e59e6dea4dea5f09c04362d545...,2026-09-04,September-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-3.00
3,c079609fd772bcb05b9f67e1abad6af5c87e3fbb5792b4...,2026-09-04,September-26,03076275,Joint,Nationwide,ICELAND KINGSBURY GB,APPLEPAY 4914,NaN,-3.85
4,e5790b4c063f3ab2f143b4142ac15c5466373ae30291ff...,2026-09-04,September-26,03076275,Joint,Nationwide,TESCO STORES 2126 BOREHAMWOOD GB,APPLEPAY 9160,NaN,-9.20
5,cc3dff86837e9462f2571c0e5a4015bc6bf87e92d39176...,2026-09-05,September-26,03076275,Joint,Nationwide,SQ *LITTLE LION ENTERTAIN London GB,APPLEPAY 4914,NaN,-15.00
6,6a3b99555370a760fa85222e3aa6e72849401e9df8ef40...,2026-09-07,September-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 9160,NaN,-5.10
7,6e49e5d592b2e9c4e6651a6dd21b20ead0e8668abc3165...,2026-09-07,September-26,03076275,Joint,Nationwide,MORRISONS COLINDALE - 373 COLINDALE GB,APPLEPAY 9160,NaN,-20.36
8,a20a2c9b3b8d455290c4a7b9eb288c9acbb09d0146aa5a...,2026-09-12,September-26,03076275,Joint,Nationwide,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,APPLEPAY 4914,NaN,-5.96
9,3cf06dce5025451e49cf6974ee94393b89360eb868c40d...,2026-09-14,September-26,03076275,Joint,Nationwide,WAITROSE STORES HARROW WEALD GB,APPLEPAY 9160,NaN,-10.46

In [9]:
transactions_metadata_df.head(10)

,event_id,llm_merchant,llm_category,manual_merchant,manual_category,manual_amount,hidden
0,bd111b5020ee5a1518b14556646d5602093349e4388f1f...,DOMINO S PIZZA MILTON KEYNES GB,dining,NaN,NaN,NaN,False
1,052ebaee9177cb9a0f194c620602fc7f808fe6bd08f08a...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,False
2,f6a0625d165905b80279e59e6dea4dea5f09c04362d545...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,False
3,c079609fd772bcb05b9f67e1abad6af5c87e3fbb5792b4...,ICELAND KINGSBURY GB,groceries,NaN,NaN,NaN,False
4,e5790b4c063f3ab2f143b4142ac15c5466373ae30291ff...,TESCO STORES 2126 BOREHAMWOOD GB,groceries,NaN,NaN,NaN,False
5,cc3dff86837e9462f2571c0e5a4015bc6bf87e92d39176...,SQ *LITTLE LION ENTERTAIN London GB,dining,NaN,NaN,NaN,False
6,6a3b99555370a760fa85222e3aa6e72849401e9df8ef40...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,False
7,6e49e5d592b2e9c4e6651a6dd21b20ead0e8668abc3165...,Morrisons,groceries,NaN,NaN,NaN,False
8,a20a2c9b3b8d455290c4a7b9eb288c9acbb09d0146aa5a...,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,groceries,NaN,NaN,NaN,False
9,3cf06dce5025451e49cf6974ee94393b89360eb868c40d...,Waitrose,groceries,NaN,NaN,NaN,False

In [10]:
transactions_df.shape

(132, 10)

In [11]:
transactions_metadata_df.shape

(132, 7)

In [12]:
transactions_db.upload_transactions_to_db(transactions_df, 
                                       db_client, 
                                       table_name="transactions")
transactions_db.upload_transactions_to_db(transactions_metadata_df, 
                                       db_client, 
                                       table_name="transactions_metadata",
                                       exclude_columns=["manual_merchant", "manual_category", "manual_amount", "manual_date", "hidden"])

APIResponse(data=[{'event_id': 'bd111b5020ee5a1518b14556646d5602093349e4388f1f3bbb0b36700de14a47', 'llm_merchant': 'DOMINO S PIZZA MILTON KEYNES GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '052ebaee9177cb9a0f194c620602fc7f808fe6bd08f08a377eb9ccf0f64e9c9d', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'f6a0625d165905b80279e59e6dea4dea5f09c04362d5456ffc49a2f325bc21ca', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'c079609fd772bcb05b9f67e1abad6af5c87e3fbb5792b4a32ab1993c579df752', 'llm_merchant': 'ICELAND KINGSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'e5790b4c063f3ab2f143b4142ac15c5466373ae30291ff8583aece58d3827079', 'llm_merchant': 'TESCO STORES 2126 BOREHAMWOOD GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'cc3dff86837e9462f2571c0e5a4015bc6bf87e92d391765914858d6c82f31144', 'llm_merchant': 'SQ *LITTLE LION ENTERTAIN London GB', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '6a3b99555370a760fa85222e3aa6e72849401e9df8ef40ef8abd0d97618a2199', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '6e49e5d592b2e9c4e6651a6dd21b20ead0e8668abc3165ce3041d600b61bc35d', 'llm_merchant': 'Morrisons', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'a20a2c9b3b8d455290c4a7b9eb288c9acbb09d0146aa5ae2a646ac0a89006a1c', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '3cf06dce5025451e49cf6974ee94393b89360eb868c40d575038f087d24dd685', 'llm_merchant': 'Waitrose', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '35a02a1f2fd0d2c6f1ddee2c2f098ad33bf0c500462fb0d3a42627989c4339d4', 'llm_merchant': 'Tesco', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'd8b9dc9c2e87e9526d8456ffb3c5fc6af0694bf918ed6237febdd369f40977f2', 'llm_merchant': 'WWW.EVERYONEACTIVE.COM HINCKLEY GB', 'llm_category': 'health', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '5d1003108a1d690502ee3b6d9c143a5046883effb4984d74d4de20f65c9607a3', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '76e0761651dce0ebd7d7084cfe4723d6a8339bff2ea6040bc40fb5f9b39aea0c', 'llm_merchant': 'TAJ PATEL', 'llm_category': 'housing', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '83ea38845be1bd862b48b3d5c6847af6a5875b7154cd8d09501d25f968870e40', 'llm_merchant': '071490 77608825 Withdrawal 22 September 2026', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'd862986d7d010e043e6eb8fbde5b36557d9d795304c9b340ccf82e68c61f8368', 'llm_merchant': 'TAJ PATEL', 'llm_category': 'housing', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '20807ef58b5b1749f5352d43deae7bb794b6cf3b0f8dacece0d952243c5af037', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '60eda1274e089981c045f16d9763352b1fbb820f1a7e3936e028e091452117c6', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '3ab14d7a2d6aa6d4354a6a1eba06529a0d41dd1b9bd917adc8524f13bba29414', 'llm_merchant': 'TESCO STORES 2126 BOREHAMWOOD GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '53b72cc4f35b510efa1cc757f2d22fbb963f66453aca7785d944f0275e217108', 'llm_merchant': 'MAB Retail - Online App', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'c24133997bfb8c5201a9ef5ff94db6941946413ab8780c7c70bce51cdb851403', 'llm_merchant': 'MAB RETAIL - ONLINE APP ONLINE GB', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'e67b7435156c46495d19df75c25769c2760930ce3c966798a5c5df20570a40f2', 'llm_merchant': 'MAB Retail - Online App', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '87b0ea5a32cfac25146df880b298ad824b20bb76d549539c809b5fecbfe0bcc7', 'llm_merchant': 'ASDA STORES', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'a97c0fe39fb6b21ad2c255c60e7a907c41996f130762c22b988d31dc6c7b0bad', 'llm_merchant': 'MARKS&SPENCER PLC LONDON GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'fb690721c0a7316eeaa551d25514119c406d751cadfd4f4a02efa22d2bbdaa9f', 'llm_merchant': 'Cards Direct Borehamwood GB', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'ff53a04f5b84147bd8a3a4b400508a0b61f403bb84ea6b9aa38ab098712b1218', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'e661294f92244ebc2885baccad3468304bf47cddcd27b288a1572c993b984e75', 'llm_merchant': 'Tshirt Studio', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'b9949f0133d286e8e622bcfa27637589764107b26a0838d7fcb4629b630667f6', 'llm_merchant': '070436 34490057 Credit 28 September 2026', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '6cd16c8fafc62abcea0a8c9dfe7ed36bcb2d09d265a5de8ee526f8e8ac492c8e', 'llm_merchant': 'MORRISONS QUEENSBURY - 30 QUEENSBURY GB', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '71d07654995f7058e73d9663d98a88d61d77241b8e84d7864dfe5f2777813038', 'llm_merchant': 'TESCO STORE 2126 2126TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '46cb84fdc5918d35efac30585baf3dbbd07735b30a4d758015aa20823083a5f2', 'llm_merchant': 'TFL TRAVEL CHARGE', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '85cc133b200c9b11966fbb126b98e11ad069cf0861b9342190761396dbd0e544', 'llm_merchant': 'COSTCO', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '88f2d597758917d2bbfdde4be8a2d9457c6aedf75b0215b563cdf37046ca6585', 'llm_merchant': 'TFL TRAVEL CHARGE', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'f30fbddfa9c3ac36d6c22791c21c9e82bbedc9ce36baa68164005610ac3b173c', 'llm_merchant': "Sainsbury's", 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'ec9692ad390189144f2a34ac3703ed904e530609a5f8a7c23da7dc8841faccff', 'llm_merchant': 'TFL TRAVEL CHARGE', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '15cd482b059f13102f337f060b7c2743afbfc717246f9c49351d17bfd1aa28b2', 'llm_merchant': 'O2', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'faafdbafd627ce61cbf93bc789e5e40692a0e1806f440796020e1c12a84aeea0', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE 0000000000000000', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '1da9e0fb441618ea27e91fde076793411058193d3e730441c54835ce586e36af', 'llm_merchant': 'Amazon', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '64d7d793965c8065b2407ea9c8ce97fd4d88900cb0e8123044a9eb3e136a87e7', 'llm_merchant': 'THE GYM LTD', 'llm_category': 'health', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'a9be9840b79cb5962f195833c789cdc4a0ecea67e93ae997711e63846fd06396', 'llm_merchant': 'RADHIKA PATEL', 'llm_category': 'housing', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '3ef67d83a3f0473b37426cfbd65dd241034a56c4fd8c84a955ec0c06db0c2f99', 'llm_merchant': 'PAYPAL', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'c2dcd1636613eefdeab21770fc640d499f2844d0a5fb45c442a97dbbf525531f', 'llm_merchant': 'PAYPAL', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '042cc8c5e69508ad1ef2df7df2ee5c5ca2d8ad8fe927f3abaf3be2bb3e742cdc', 'llm_merchant': 'TAJ JAMIE R PATEL', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'd48960ee98f1508438e53c920f965bc4873da2034aa7fee19e2062790903335d', 'llm_merchant': 'Tesco', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'b16dfea66a3a4db19d12d6434168790a114e8092b9a726b208f5bd59ec7d0a17', 'llm_merchant': 'Nationwide', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'd12b048c35d4df6e56075eb89d2de304c4c85cfb508dd213663f92ea05770667', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '3529412c546b4257f3fc2d692e721cca56a6a6e455e62e303cd9af9e76fa3604', 'llm_merchant': 'PAYPAL', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'e36526ca8c62efcd0ac692a541d0b936c670e243e5626432e994bf9d4b1a51de', 'llm_merchant': 'RADHIKA PATEL', 'llm_category': 'housing', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'c31d2a8d36a0b3492ea7b629cbdc671a4cda0ca940af3cdc3528766e9860b606', 'llm_merchant': '071120 59759923 Credit 24 September 2026', 'llm_category': 'shopping', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '0874dc916819936a307ac279c06687d26da2fb8287ad68e06b26e21a2a146407', 'llm_merchant': 'RADHIKA PATEL', 'llm_category': 'housing', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '71eb7de4a3315c8e213af1aabbab19cb94b7f3391fe8e06f144ea93bfd45da20', 'llm_merchant': 'APPLE.COM/BILL 08001076285 IE', 'llm_category': 'subscriptions', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'beafb9eada52f8dc30231682a585e8461e9e12f7370735818185a3b92dcadc2e', 'llm_merchant': 'HOME BARGAINS BOREHAMWOOD', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '1b54e67c5581d019390a7ef597a006678c976ad02457b88ea0ec115857c00899', 'llm_merchant': 'Greggs', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '2be96f30a7a54a001e94a78d3ef4b4e2f03ba695e08b669d310d040fb3b4a8f7', 'llm_merchant': 'SOUTHERN FUNDING', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '7daaa8bf8d938a717573504c6243d17193060e3b30c711d2a1aa9ce567d3a1b4', 'llm_merchant': '071490 77608825 Withdrawal 28 September 2026', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'da701a44ee03e10fc6294e292cbc2401de8b0fe77a98ff8dc9d494043507cc5d', 'llm_merchant': 'TAJ JAMIE R PATEL', 'llm_category': 'dining', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '7f5cb8445dac1bb5e3d9894f42194cdc9f129eb97a179b90bc3ed98e7aa0f974', 'llm_merchant': '071986 03076275 Withdrawal 28 September 2026', 'llm_category': 'salary', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '93efa2510e4e4b7928971fcc61bb7cd79a128d22527eec415d5ff355cc0a2ff7', 'llm_merchant': 'RADHIKA PATEL', 'llm_category': 'housing', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'b649c01d8813ab502f39da4b424deac7e1794f27840bd74a7674389579037f26', 'llm_merchant': 'TESCO PETROL 5288 5288T', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '3b9ec5314b07efe916de54effbe5206a773243543ca14a1e3836a07de6134669', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '482229d52caf29fe39230d74b6936d1eee42f6b27f3a2f19ae0ad4b3d42b261e', 'llm_merchant': 'TESCO PETROL 5288 5288T', 'llm_category': 'transport', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '8e3a835f633bec83bac258bb3ee7070b4026dfff10d9eba75408247dae47ca4b', 'llm_merchant': 'WM MORRISONS STORES - Q', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'd0dcc0937705c8f8196bde8f7fbdac0e914907e5e5795e06314a9f1d5300e9b7', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '5a270d9c342d06ff5d8929d206320600fd82e868491ab630b455d6d68a046213', 'llm_merchant': 'WM MORRISONS STORES - Q', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '9146f71c19fb39b6bcb5a261cb9296e35bd357bca4f9dfefa7b2afc85dcc7f2b', 'llm_merchant': 'WM MORRISONS STORES - Q', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'b58ef0857183718bf59b8443e358ba6b3dd91a015d886045fc801bab5a39944c', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'f65adcc5c256aec6d09e6692266ccefa3fe55fdf1ddc35df30ce6131d23c7da0', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': '1c9d05c82b42ab9629ef58a2db3479357e342b1c2590c3f9f32c946544ecc9a2', 'llm_merchant': 'TESCO STORE 5620 5620TE', 'llm_category': 'groceries', 'manual_merchant': None, 'manual_category': None, 'manual_amount': None, 'hidden': False, 'updated_at': '2026-10-01T12:44:32.176718+00:00'}, {'event_id': 'b48559823ef8717045c99b6