In [1]:
from pathlib import Path
from spending_tracker.data_processing.statements import _BANK_TO_PROCESSING_FUNCTIONS, _BANK_TO_DATA_LOADING_FUNCTIONS

In [ ]:
user = "Radhika"
bank = "Nationwide"
account_id = "34490057"
month = "August-26"

data_path = Path().resolve().parent / "data" / "transactions" / "raw" / user / bank / account_id / month 


statement_path = next(
    (p for p in data_path.glob("statement.*") if p.suffix in {".csv", ".pdf"}),
    None
)
data_save_path = Path().resolve().parent / "data" / "transactions" / "processed" / user / bank / account_id / month / "statement.csv"
print(statement_path)

/Users/taj/Documents/Spending-Tracker-Agent/data/transactions/raw/Joint/Nationwide/03076275/July-26/statement.csv

In [3]:
raw_statement_df = _BANK_TO_DATA_LOADING_FUNCTIONS[bank](statement_path)

In [4]:
raw_statement_df.head()

,Date,Transaction type,Description,Paid out,Paid in,Balance
0,07 Jul 2026,Bank credit,TAJ PATEL,NaN,£500.00,£1032.43
1,08 Jul 2026,Contactless Payment,TESCO STORES 5620 LONDON GB APPLEPAY 4914,£3.80,NaN,£1028.63
2,09 Jul 2026,Bank credit,KAMLA PATEL,NaN,£100.00,£1128.63
3,09 Jul 2026,Bank credit,PRIYA CHAUHAN,NaN,£190.00,£1318.63
4,09 Jul 2026,Transfer to,071490 77608825 Withdrawal 09 July 2026,£290.00,NaN,£1028.63

In [5]:
cleaned_df = _BANK_TO_PROCESSING_FUNCTIONS[bank](raw_statement_df, account_id=account_id)

In [6]:
cleaned_df.head(10)

,event_id,date,month,merchant,type,category,amount,other_details,account_id,user,raw_merchant,raw_amount,bank,hidden
0,4dfe72a057bb9e273208e3470ea91f0a64779283185e80...,2026-07-07,July-26,TAJ PATEL,Bank credit,None,500.00,,03076275,Joint,TAJ PATEL,500.00,Nationwide,False
1,897b964f7d4d2e001d6149f152bec20e3413e690eae85c...,2026-07-08,July-26,TESCO STORES 5620 LONDON GB,Contactless Payment,None,-3.80,APPLEPAY 4914,03076275,Joint,TESCO STORES 5620 LONDON GB,-3.80,Nationwide,False
2,c70e40fe2579c0e27e76a1d16f8a7d91d3b5f4dd16b485...,2026-07-09,July-26,KAMLA PATEL,Bank credit,None,100.00,,03076275,Joint,KAMLA PATEL,100.00,Nationwide,False
3,2f052381c3482ca02d6bd29a6ab5e1c764f2cae4414962...,2026-07-09,July-26,PRIYA CHAUHAN,Bank credit,None,190.00,,03076275,Joint,PRIYA CHAUHAN,190.00,Nationwide,False
4,f6a9bb8f21bc3aac5928d8395d55a38ec44b4ae25aa3d2...,2026-07-09,July-26,071490 77608825 Withdrawal 09 July 2026,Transfer to,None,-290.00,,03076275,Joint,071490 77608825 Withdrawal 09 July 2026,-290.00,Nationwide,False
5,959b86f5d0ae066ddbefe59c6ba07d42e84f5bf2e7f678...,2026-07-10,July-26,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,Contactless Payment,None,-9.36,APPLEPAY 4914,03076275,Joint,MORRISONS QUEENSBURY - 30 QUEENSBURY GB,-9.36,Nationwide,False
6,2c25293fb239d900915db5245fc12bca371c76276e286d...,2026-07-11,July-26,ASDA SUPERSTORE COLINDALE GB,Contactless Payment,None,-5.00,APPLEPAY 9160,03076275,Joint,ASDA SUPERSTORE COLINDALE GB,-5.00,Nationwide,False
7,eae2b36adcf5123c180c574db84cd29b56170cbf07958c...,2026-07-11,July-26,FUNKY PIGEON BRISTOL GB,Visa purchase,None,-7.29,APPLEPAY 9160,03076275,Joint,FUNKY PIGEON BRISTOL GB,-7.29,Nationwide,False
8,13d5d5ad99a408268ed354a262e3799425b332d0b54be2...,2026-07-11,July-26,MARKS&SPENCER PLC LONDON GB,Contactless Payment,None,-7.43,APPLEPAY 9160,03076275,Joint,MARKS&SPENCER PLC LONDON GB,-7.43,Nationwide,False
9,c10b670b09fc44c817cbbe8359d89a61e87142dcf02045...,2026-07-11,July-26,M&S SALFORD INTERNET GB,Visa purchase,None,-25.00,APPLEPAY 5176,03076275,Joint,M&S SALFORD INTERNET GB,-25.00,Nationwide,False